<?php
namespace PaxPamir;

const OPTION_OPEN_HANDS = 100;
const OPTION_OPEN_HANDS_DISABLED = 0;
const OPTION_OPEN_HANDS_ENABLED = 1;

const OPTION_WAKHAN = 101;
const OPTION_WAKHAN_DISABLED = 0;
const OPTION_WAKHAN_BASIC = 1;
const OPTION_WAKHAN_IMPROVED = 2;
const OPTION_WAKHAN_CUSTOM = 3;

const OPTION_WAKHAN_VARIANT_SAVVY_PURCHASING = 102;
const OPTION_WAKHAN_VARIANT_SAVVY_PURCHASING_DISABLED = 0;
const OPTION_WAKHAN_VARIANT_SAVVY_PURCHASING_ENABLED = 1;

const OPTION_WAKHAN_VARIANT_SPY_MOVEMENT = 103;
const OPTION_WAKHAN_VARIANT_SPY_MOVEMENT_DISABLED = 0;
const OPTION_WAKHAN_VARIANT_SPY_MOVEMENT_ENABLED = 1;

const OPTION_WAKHAN_VARIANT_STEADFAST_PRAGMATIC_LOYALTY = 104;
const OPTION_WAKHAN_VARIANT_STEADFAST_PRAGMATIC_LOYALTY_DISABLED = 0;
const OPTION_WAKHAN_VARIANT_STEADFAST_PRAGMATIC_LOYALTY_ENABLED = 1;

const OPTION_WAKHAN_AUTO_RESOLVE = 105;
const OPTION_WAKHAN_AUTO_RESOLVE_DISABLED = 0;
const OPTION_WAKHAN_AUTO_RESOLVE_ENABLED = 1;
