<?php
namespace PaxPamir;

const OPTION_OPEN_HANDS = 100;
const OPTION_OPEN_HANDS_DISABLED = 0;
const OPTION_OPEN_HANDS_ENABLED = 1;

const OPTION_WAKHAN = 101;
const OPTION_WAKHAN_DISABLED = 0;
const OPTION_WAKHAN_ENABLED = 1;